name: Deploy to EC2 (systemd)

on:
  push:
    branches: [ "master" ]   

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish (Release)
        run: dotnet publish -c Release -o out

      - name: Archive artifacts
        run: cd out && tar -czf ../app.tar.gz .

      - name: Upload to server (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          # port: ${{ secrets.SSH_PORT }}   # ← розкоментуй, якщо потрібен інший порт
          source: "app.tar.gz"
          target: "/opt/telegram-bot"

      - name: Unpack, switch symlink, restart service (SSH)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          # port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            ts=$(date +%Y%m%d%H%M%S)
            rel="/opt/telegram-bot/releases/$ts"
            mkdir -p "$rel"
            tar -xzf /opt/telegram-bot/app.tar.gz -C "$rel"
            rm -f /opt/telegram-bot/app.tar.gz
            ln -sfn "$rel" /opt/telegram-bot/current
            sudo systemctl restart telegram-bot
            systemctl is-active telegram-bot
