name: Deploy to Lightsail Container Service
on:
  push:
    branches: [ "main", "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_PAGER: ""   # щоб aws-cli не відкривав пейджер

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install lightsailctl and jq
        run: |
          curl -s https://s3.amazonaws.com/amazonlightsail-us-east-1/lightsailctl/latest/linux-amd64/lightsailctl -o lightsailctl
          sudo mv lightsailctl /usr/local/bin/lightsailctl
          sudo chmod +x /usr/local/bin/lightsailctl
          sudo apt-get update && sudo apt-get install -y jq

      - name: Debug identity and service
        run: |
          aws sts get-caller-identity
          echo "REGION=${{ secrets.AWS_REGION }}"
          echo "SERVICE=${{ secrets.LIGHTSAIL_SERVICE_NAME }}"
          aws lightsail get-container-services \
            --service-name "${{ secrets.LIGHTSAIL_SERVICE_NAME }}" \
            --region "${{ secrets.AWS_REGION }}"

      - name: Select Dockerfile
        id: df
        run: |
          if [ -f Dockerfile.hardened ]; then
            echo "path=Dockerfile.hardened" >> $GITHUB_OUTPUT
          else
            echo "path=Dockerfile" >> $GITHUB_OUTPUT
          fi

      - name: Build image
        run: docker build -t bot:latest -f ${{ steps.df.outputs.path }} .

      - name: Push image to Lightsail (capture image URI robustly)
        id: push
        run: |
          set -euo pipefail
          # Захоплюємо І stdout, І stderr (lightsailctl часто пише JSON у stderr)
          aws lightsail push-container-image \
            --service-name "${{ secrets.LIGHTSAIL_SERVICE_NAME }}" \
            --label bot \
            --image bot:latest \
            --region "${{ secrets.AWS_REGION }}" 2>&1 | tee /tmp/push.out

          echo "===== raw push output ====="
          sed -n '1,200p' /tmp/push.out || true

          # 1) спроба зчитати JSON-поле .image
          URI="$(jq -r '.image // empty' /tmp/push.out 2>/dev/null || true)"

          # 2) спроба витягнути з рядка "image: <value>"
          if [ -z "$URI" ] || [ "$URI" = "null" ]; then
            URI="$(grep -oE 'image:\s*[^[:space:]]+' /tmp/push.out | head -n1 | sed 's/image:\s*//')"
          fi

          # 3) фолбек на SERVICE:bot
          if [ -z "$URI" ] || [ "$URI" = "null" ]; then
            URI="${{ secrets.LIGHTSAIL_SERVICE_NAME }}:bot"
            echo "Did not parse image URI from output. Falling back to: $URI"
          else
            echo "Parsed image URI: $URI"
          fi

          echo "image_uri=$URI" >> $GITHUB_OUTPUT

      - name: Create deployment spec (no publicEndpoint)
        run: |
          cat > spec.json <<'JSON'
          {
            "serviceName": "${{ secrets.LIGHTSAIL_SERVICE_NAME }}",
            "containers": {
              "bot": {
                "image": "${{ steps.push.outputs.image_uri }}",
                "environment": {
                  "BOT_TOKEN": "${{ secrets.BOT_TOKEN }}",
                  "MONOBANK_TOKEN": "${{ secrets.MONOBANK_TOKEN }}",
                  "MONOBANK_ACCOUNT_ID": "${{ secrets.MONOBANK_ACCOUNT_ID }}",
                  "DB_CONNECTION_STRING": "${{ secrets.DB_CONNECTION_STRING }}",
                  "CHANNEL_USERNAME": "${{ secrets.CHANNEL_USERNAME }}",
                  "ADMIN_CHAT_ID": "${{ secrets.ADMIN_CHAT_ID }}",
                  "BOT_USERNAME": "${{ secrets.BOT_USERNAME }}",
                  "MONO_JAR_URL": "${{ secrets.MONO_JAR_URL }}"
                },
                "command": ["TelegramOlxBot.dll"],
                "ports": {}
              }
            }
          }
          JSON
          echo "===== spec.json ====="
          cat spec.json

      - name: Deploy to Lightsail
        run: |
          aws lightsail create-container-service-deployment \
            --service-name "${{ secrets.LIGHTSAIL_SERVICE_NAME }}" \
            --cli-input-json file://spec.json \
            --region "${{ secrets.AWS_REGION }}"

      - name: Verify deployment
        run: |
          aws lightsail get-container-services \
            --service-name "${{ secrets.LIGHTSAIL_SERVICE_NAME }}" \
            --region "${{ secrets.AWS_REGION }}"
